package com.infotel.gg.service;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.loader.custom.Return;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.infotel.gg.DTO.CityDTO;
import com.infotel.gg.DTO.CookingStyleDTO;
import com.infotel.gg.DTO.EateryDTO;
import com.infotel.gg.DTO.ImageDataDTO;
import com.infotel.gg.DTO.MenuDTO;
import com.infotel.gg.DTO.ReviewDTO;
import com.infotel.gg.DTO.SearchCriteriaDTO;
import com.infotel.gg.dao.BookingDAO;
import com.infotel.gg.dao.CityDAO;
import com.infotel.gg.dao.CookingStyleDAO;
import com.infotel.gg.dao.EateryDAO;
import com.infotel.gg.dao.ImageDataDAO;
import com.infotel.gg.dao.ReviewDAO;
import com.infotel.gg.exception.GGourmandException;
import com.infotel.gg.hibernate.CityDAOHbn;
import com.infotel.gg.hibernate.CookingStyleDAOHbn;
import com.infotel.gg.hibernate.EateryDAOHbn;
import com.infotel.gg.model.CookingStyle;
import com.infotel.gg.model.Eatery;
import com.infotel.gg.model.Address;
import com.infotel.gg.model.City;
import com.infotel.gg.model.Country;
import com.infotel.gg.model.EateryTag;
import com.infotel.gg.model.ImageData;
import com.infotel.gg.model.PracticalInformation;
import com.infotel.gg.model.Region;
import com.infotel.gg.model.Booking;
import com.infotel.gg.model.Review;
import com.infotel.gg.model.EateryResult;
import com.infotel.gg.model.SearchCriteria;
import com.infotel.gg.DTO.OrderDTO;


@Service("CatalogService")
@Transactional
public class CatalogServiceImpl implements CatalogService {
	
	private static ObjectMapper mapper = new ObjectMapper(new YAMLFactory());

	private final static Logger log = LogManager.getLogger(CatalogServiceImpl.class);

	@Autowired
	private CookingStyleDAO cookingStyleDAO;
	
	@Autowired
	private EateryDAO eateryDAO;
	
	@Autowired
	private ImageDataDAO imageDataDAO;
	
	@Autowired
	private CityDAO cityDAO;

	@Autowired
	private ReviewDAO reviewDAO;

	@Autowired
	private BookingDAO bookingDAO;

	@Override
	public List<CookingStyleDTO> getAllCookingStyles() {
		List<CookingStyleDTO> result = new ArrayList<CookingStyleDTO>();
		List<CookingStyle> cookingstyles = cookingStyleDAO.listAll();
		for(CookingStyle cs : cookingstyles){
			CookingStyleDTO cookingStyleDto = new CookingStyleDTO();
			cookingStyleDto.setId(Integer.toString(cs.getId()));
			cookingStyleDto.setName(cs.getName());
			result.add(cookingStyleDto);
		}
		return result;
	}
	
	@Override 
	public String getCookingNameById(int id){
		if(id > 0){
			return cookingStyleDAO.read(id).getName();
		}
		return null;
	}
	@Override
	public List<EateryDTO> getAllEateries(){
		List<EateryDTO> result = new ArrayList<EateryDTO>();
		List<Eatery> eateries = eateryDAO.listAll();
		eateries.stream().forEach(e -> result.add(transform(e, false)));
		return result;
		
	}

	@Override
	public EateryDTO findOneEatery(int id) {
		Eatery eat = eateryDAO.read(id);
		EateryDTO edto = transform(eat, true);
		return edto;
	}

	@Override
	public Eatery findOneRealEatery(int id) {
		return eateryDAO.read(id);
	}

	public EateryDTO transform(Eatery eat, boolean detail) {
		EateryDTO e = new EateryDTO();
		e.setId(eat.getId());
		e.setName(eat.getName());
		e.setExecutiveChef(eat.getExecutiveChef());

		e.setCookingStyle(eat.getCookingStyle().getName());
		e.setCookingStyleid(eat.getCookingStyle().getId());
		Address ad = eat.getAddress();
		if (ad != null) {
			e.setStreet(eat.getAddress().getStreet());
			e.setPostCode(ad.getPostCode());

			City ci = ad.getCity();
			if (ci != null) {
				e.setCity(ci.getName());
				e.setCityid(ci.getId());

				Region re = ci.getRegion();
				if (re != null)
					e.setRegion(re.getName());
				Country co = ci.getCountry();
				if (co != null) {
					e.setCountry(co.getName());
				}
			}

		}

		List<Integer> imageIds = null;
		List<ReviewDTO> reviews= null;
		PracticalInformation pi = eat.getPracticalInformation();
		e.setDescription(eat.getDescription());
		if (pi != null) {
			e.setPrice(pi.getPrice());
			e.setHoursOfOperation1(pi.getHoursOfOperation1());
			e.setHoursOfOperation2(pi.getHoursOfOperation2());
			e.setPaymentOptions(pi.getPaymentOptions());
			e.setGettingThere(pi.getGettingThere());
			e.setParking(pi.getParking());
		}
				if (detail) {
					imageIds = imageDataDAO.findBigByEateryId(eat.getId());
					e.setImageIds(imageIds);
		
					// Menu
					
					try {
						MenuDTO menu = mapper.readValue(eat.getMenu().getContent(), MenuDTO.class);
						e.setMenu(menu);
					} catch (Exception e1) {
						log.error("Echec d�s�rialisation du menu", e1);
		
					}
					
					//review
					reviews = reviewDAO.listAllByEateryId(eat.getId()).stream().map(r -> transform(r))
							.collect(Collectors.toList());
					 e.setReviews(reviews);
					 
				} else {
					imageIds = imageDataDAO.findSmallByEateryId(eat.getId());
					e.setImageIds(imageIds);
				}
				if (!imageIds.isEmpty()) {
					e.setImageId(imageIds.get(0));
				}

		List<EateryTag> eatag = eat.getEateryTags();
		if(eatag != null) {
			List<String> eatagname = new ArrayList<>();
			for (int i = 0; i < eatag.size(); i++) {
				if (eatag.get(i) != null) {
					eatagname.add(eatag.get(i).getName());
				}
			}
			e.setEateryTagName(eatagname);
		}
		return e;

	}

	@Override
	public ImageDataDTO findImageDataById(int id) throws GGourmandException {
		ImageData image = imageDataDAO.read(id);
		ImageDataDTO imgdataDto = transform(image);
		return imgdataDto;
	}
	
	@Override
	public ImageDataDTO findImageDataDefault() throws GGourmandException {
		ImageDataDTO imgdataDto = new ImageDataDTO();
		imgdataDto.setContent("data:image/jpeg;base64, iVBORw0KGgoAAAANSUhEUgAAA0IAAAGmCAYAAABRFDTJAAACtnpUWHRteEdyYXBoTW9kZWwAAE1TybaiMBT8Gs7pXjSHSdAlICCTyCA82YEEiAxhRvn6Dv3eoheESt1K3QQqBCs37xzWgGCoeQSDWIB2ItgzwTA22mBdJwSjHkgKl39FsM3QOmJ4DfDAkzTBShhgnue+4ZvnfuOX2HU1iEBqwmlfzgoky+8O5iWwLYKRMa5htffUwLNC+xK5HFADdrVAUiRzOgokzbK44Cd5MsD/bBhMLmAYIWq/N8qTHPnDgwxOaPim13UlsyFZSYj2IqsQrJzBpBiSBivbBHf7p7slBfhDf0uEOLXSUV8VJcIdjXEyDZnrLHU0hST2DS/OZsxrbnQu4sO5OBKMtIT04zXeulDs3ex+YRspD5jkCZg3fFGbLzycqscy19DcYtEsefLwjD/pYqHlPf5mqt+EbX0W7ZcnWRvaquvRfC6cEkr0Y3J056jwhVsCcxjKsqwrrXLKPlReeTaKkZlO9/CVKO0m23uTGVnxB715WOgadqY8YHy4T8tx15ezXNVBU9Bi04stjz1MmjvffZgwvypHtFK0pdfOLZB9aA805ayqB+ZptPEJ1etp3CL+kLh9ZIPR2KJQCoqw/kw+bsk81YP8Zk6Gf3tiG8wYGarN0hOE+VANUIEPdFdTL1ZF+hY6sahF8bP3g80q3KzxetGZpMRIJ5pJUeAmj6LThUtqdIn4mcp7ZZVXu5LNgZu7GTAV5eEfJbW9jFOo6hlQGsPOZK85h1NLzZQjUEqqqEKA46Bm9TvTq7A+m/2Xf8mS4RTqaszcfJdauisST2WLveIvszXeEWhK1/jEcL10syoMCURahz2qqe20jHkKQXCqlttWHAWLxwmWtlGKc+mxB9a4g9cT8TvkbWpZtvByD3g+Zwus4/CTX17pl/++Ada5GCeJ2mPHyvsOf9L4L5p4/nMTWeUvDYkAWwAAIABJREFUeF7t3Y9LXGfa8PHJimIZGpQ0ZoMhZWhWsbH1Na+L1Oor2oghMCRVgm6CRTpPEoMoCY9/wP4BPiQoEpM8U3wrySpBmzAQIkkVH61F1jdiayq6KUNDJBvToKQMFcXNy309z5x1TVt/zTlzzn2+AzLdzZz7vq7PfX7c18z5sePVq1evPB6P5/2c/+X59psJ9Z+8EEAAAQQQQAABBBBAAAEtBQoK/4/nq6FBz45oIZRf8H88Bfn/29Pa2ur593//d/lLS0vTMnmSQgABBBBAAAEEEEAAAXcIzM3Nef7jP/5D/hoaGjwjo//PMzryX/9aCKn/44cffpAPXblyxSiIdu3a5Q4lskQAAQQQQAABBBBAAAEtBF68eGEUQGfPnpXa5u233/aoH4B+sRCKZh0Oh2XBzz77zCiIUlJStEAhCQQQQAABBBBAAAEEENBTYGFhwSiAPv30U6llfD6fkey6hVD0k48ePZKGOjs7pZGmpibPm2++qacaWSGAAAIIIIAAAggggIAjBX766SdPc3Oz1C41NTVSuxw4cOC1XDZcCEWXnJ6elka7u7uNX4i8Xq8jkQgaAQQQQAABBBBAAAEE9BCIRCLGL0BVVVVSq2RmZv5qcpsuhKItfffdd9LRF198YRREycnJeiiSBQIIIIAAAggggAACCDhCYHFx0SiAPv74Y6lN3n333XVj33IhFG15cnJSOg6FQnK6nOo4MTFx3Y75AAIIIIAAAggggAACCCCwVYHl5WWpQ9RpcH6/X+qQ7OzsDTe37UIo2tPExIQE0tfXZ1xD9Lvf/W7DgfBBBBBAAAEEEEAAAQQQQGA9gX/84x/GNUDl5eVSe+Tk5Ky32Gv/HrNCKNrygwcPpCAaGBgwTpnbdFQsgAACCCCAAAIIIIAAAgisEYg+B6ikpERqjUOHDm3ZKOaFUDSSv/71r1IQffXVVxLk+fPntxwkCyKAAAIIIIAAAggggIB7BS5duiS1xYcffii1xR//+MdtY5hWCEUjGx0dlaDVu7qGSD3FlRcCCCCAAAIIIIAAAgggsJ5Aa2urnAaXn58vBZB6j9XL9EIoGujIyIgUROPj45JEfX19rHKgHQQQQAABBBBAAAEEENBIoK2tTWqH3NxcqR0KCgpinp1lhVA08qGhIUnq4cOHklRdXV3Mk6JBBBBAAAEEEEAAAQQQcJ5Ae3u71AoHDx6UWqGoqMi0JCwvhKKZDA4Oys9cf/vb3yTJ06dPm5YkDSOAAAIIIIAAAggggIB9Ba5duyYF0B/+8Ae5nKa4uNj0YONWCEUz6+/vl6TD4bAk/emnn5qeNB0ggAACCCCAAAIIIIBA/AU+++wz+XHE5/PJjyOlpaWWBRX3Qiia6b1796Qgmp2dFYTa2lrLEOgIAQQQQAABBBBAAAEErBPo6OiQuX96errM/cvKyqzr/H96sk0hFM387t27gvL8+XNBqampsRyFDhFAAAEEEEAAAQQQQCD2Ap2dnTLX3717t8z1jxw5EvtONtii7QqhaNx37twRpIWFBUE6efLkBlPiYwgggAACCCCAAAIIIGAngRs3bsjcPiUlReb2R48ejXt4ti2EojKhUEjQIpGIXENUVVUVdzQCQAABBBBAAAEEEEAAgfUFuru75Rogr9crBZDf719/IYs+YftCKOpw69YtKYiWl5cF8cSJExYR0Q0CCCCAAAIIIIAAAghsRuDmzZsyd09MTJS5+/HjxzezuCWfdUwhFNXo6ekR1B07dghqRUWFJVB0ggACCCCAAAIIIIAAAr8t0NvbK3P1V69eyVy9srLStmSOK4SiktEqMykpSZCPHTtmW2QCQwABBBBAAAEEEEBAZ4Hbt29LAbS0tOSYs7ccWwhFV6Suri5Bt+N5hzqv7OSGAAIIIIAAAggggMDq6/nVjxPV1dWOQXF8IRSVvn79uhREqamptrkThWPWAgJFAAEEEEAAAQQQQGATAtE7PM/Pz8vc+9SpU5tY2h4f1aYQinJ+/vnnUhDt2bNHBqW8vNwe0kSBAAIIIIAAAggggIDDBfr6+mSu/ezZM5lrf/LJJ47NSLtCKDoS0afV7tu3Twbp8OHDjh0kAkcAAQQQQAABBBBAIJ4C9+/flwLoyZMnMreura2NZzgx6VvbQiiqEwwGZdB8Pp8MWmlpaUzgaAQBBBBAAAEEEEAAAd0F+vv7ZS4dDodlLh0IBLRJWftCKDpSV69elUHMzMyUQSwuLtZmEEkEAQQQQAABBBBAAIFYCgwODsrceXp6WubOZ86ciWXztmjLNYVQVPvy5csyqO+9954MamFhoS0GgiAQQAABBBBAAAEEEIi3wPDwsMyVv/32W5krnzt3Lt4hmda/6wqhqGRbW5sMcm5urqepqcnzwQcfmIZMwwgggAACCCCAAAII2Fng66+/lrnxgwcPpACqr6+3c7gxic21hVBUr6WlRQY9Pz9fBl2980IAAQQQQAABBBBAwA0Co6OjMhdW72ou3NjY6Ia0JUfXF0LRkb548aKsBEVFRbIS5OXluWYlIFEEEEAAAQQQQAABdwmMjY3J3HdoaEjmvhcuXHAXAIXQ6+Pd3NwsK8VHH30kK4U6dY4XAggggAACCCCAAAI6CIyPj8tc98svv5TLQ9R8160vfhH6hZFfWVmRFUT9qQeyqpXk/fffd+s6Qt4IIIAAAggggAACDhf45ptvPOoLf/VAVFX8qL+EhASHZ7W98CmEfsNvaWnJKIj8fr+sMNnZ2dsTZ2kEEEAAAQQQQAABBCwSmJyclPlsKBQyCqCkpCSLerd3NxRCGxifn3/+2SiIKisrZSXKysrawJJ8BAEEEEAAAQQQQAAB6wWmpqZk/trT02MUQG+88Yb1gdi4RwqhTQxOJBKRFUr9rPinP/1JVqqMjIxNtMBHEUAAAQQQQAABBBAwT2BmZkbmq3/5y1+Ma4C8Xq95HTq4ZQqhLQzey5cvjV+IampqZCV75513ttASiyCAAAIIIIAAAgggsH2B77//Xr6s7+zsNH4B2rlz5/Yb1rgFCqFtDO78/LxREAUCAVnpfD7fNlpkUQQQQAABBBBAAAEENi4QDodlPhoMBo0CKDU1deMNuPiTFEIxGPwff/zRKIjOnTsnK+H+/ftj0DJNIIAAAggggAACCCDwusDjx49l/nn58mWjAHrrrbeg2oQAhdAmsNb76NzcnFEQqafyqoIoPT19vcX4dwQQQAABBBBAAAEENiQwOzsr882WlhajAEpLS9vQsnzoXwUohExYI54+fWoURKoYUtcQ/f73vzehJ5pEAAEEEEAAAQQQcIPA3//+d7kGSBVB0ecA7d271w2pm5YjhZBptB7PkydPZGVtbW2lYjfRmaYRQAABBBBAAAFdBVafcdTQ0CBzyn379umarqV5UQhZwP3DDz9IQXTlyhWjINq1a5cFPdMFAggggAACCCCAgBMFXrx4YZxhdPbsWZlDvv32205MxbYxUwhZODSr7+qhTpdTK3RKSoqFEdAVAggggAACCCCAgJ0FFhYWjOdWcldic0eKQshc319s/dGjR7KCc5/3OODTJQIIIIAAAgggYEOBn376ybgGSD2nUn1hfuDAARtGqk9IFEJxHMvp6WkpiLq7u41T5njybxwHhK4RQAABBBBAAAGLBSKRiHEKXFVVlcwJMzMzLY7Cnd1RCNlg3L/77jvZAL744gujIEpOTrZBZISAAAIIIIAAAgggYIbA4uKiUQB9/PHHcpfhrKwsM7qizV8RoBCy0aoxOTkpG0QoFJKNQX0jkJiYaKMICQUBBBBAAAEEEEBgOwLLy8vGNUB+v1/me9nZ2dtpkmW3KEAhtEU4MxebmJiQDaSvr8/4hSghIcHMLmkbAQQQQAABBBBAwESBlZUV4xeg8vJymePl5OSY2CNNrydAIbSeUBz//cGDB7LBDAwMGAVRHMOhawQQQAABBBBAAIEtCKj5nPorKSmROd2hQ4e20AqLxFqAQijWoia0NzY2JncR+eqrr2TjOX/+vAm90CQCCCCAAAIIIIBALAUuXbokBdCHH34olz3k5eXFsnna2qYAhdA2Aa1cfHR0VDYm9a42JvV0YV4IIIAAAggggAAC9hJobW2VL7Hz8/PlS2z1zst+AhRC9huTdSMaGRmRgmh8fFw2rvr6+nWX4QMIIIAAAggggAAC5gq0tbXJHC03N1fmaAUFBeZ2SOvbEqAQ2hZffBceGhqSje3hw4eysdXV1cU3IHpHAAEEEEAAAQRcKNDe3i5zsoMHD8qcrKioyIUKzkuZQsh5Y/ZaxIODg7LxzczMyMZ3+vRpDbIiBQQQQAABBBBAwN4C165dkzlYRkaGzMGKi4vtHTDR/YsAhZBGK0R/f79sjOFwWDbGQCCgUXakggACCCCAAAII2EPgs88+k2uAfD6fzLlKS0vtERhRbEqAQmhTXM748L1796Qgmp2dlY2ztrbWGYETJQIIIIAAAgggYGOBjo4OmWOlp6fLHKusrMzG0RLaegIUQusJOfjf7969Kxvr8+fPZWOtqalxcDaEjgACCCCAAAIIxEegs7NT5lS7d++WOdWRI0fiEwi9xlSAQiimnPZs7M6dO7LxLiwsyMZ78uRJewZKVAgggAACCCCAgI0Ebty4IXOolJQUmUMdPXrURtERynYFKIS2K+ig5UOhkGzMkUhENubq6moHRU+oCCCAAAIIIICANQJdXV0yZ/J6vTJn8vv91nRML5YKUAhZym2Pzm7duiUb9/LysmzcJ06csEdgRIEAAggggAACCMRR4ObNmzJHSkxMlDnS8ePH4xgNXZstQCFktrCN2+/p6ZGNfceOHbKxV1RU2DhaQkMAAQQQQAABBMwR6O3tlTnRq1evZE5UWVlpTke0aisBCiFbDUd8gln97UdTU5Pn2LFj8QmEXhFAAAEEEEAAAQsFbt++LQXQ0tISZ8lY6G6XriiE7DISNoiD82FtMAiEgAACCCCAAAKmC3DdtOnEjuiAQsgRw2RtkNevX5dvR1JTU7lDirX09IYAAggggAACJgpE76Q7Pz8vc5xTp06Z2BtN212AQsjuIxTH+D7//HMpiPbs2SM7i/Ly8jhGQ9cIIIAAAggggMDWBPr6+mRO8+zZM5nTfPLJJ1triKW0EqAQ0mo4zUlm9VOU1TVEhw8fNqcjWkUAAQQQQAABBGIocP/+fU9zc7NndnZWCqDa2toYtk5TThegEHL6CFoYfzAYlG9TfD6f7ExKS0st7J2uEEAAAQQQQACBjQn09/fLnCUcDsucJRAIbGxBPuUqAQohVw13bJK9evWq7FwyMzNl51JcXBybhmkFAQQQQAABBBDYhsDg4KDMUaanp2WOcubMmW20xqK6C1AI6T7CJubX3t4uPze/9957srMpLCw0sTeaRgABBBBAAAEEfllgeHhYCqBvv/3Wo07jr6urgwqBdQUohNYl4gPrCbS1tcnOJzc3V3Y+H3zwwXqL8O8IIIAAAggggMC2Bb7++mv5UnZ8fFy+lK2vr992mzTgHgEKIfeMtemZtrS0SEGUn58vOyP1zgsBBBBAAAEEEIi1wOjoqMw51LuaczQ2Nsa6C9pzgQCFkAsG2eoUL168KDunoqIi2Tnl5eVZHQL9IYAAAggggICGAmNjYzLHGBoakjnGhQsXNMySlKwSoBCyStqF/agdlfq5+qOPPpKdlTp1jhcCCCCAAAIIILBZAXXqm5pXqLvBqTmF+uOFwHYFKIS2K8jyvymwsrIiOy71px7Iqq4hev/991FDAAEEEEAAAQTWFfjmm2/kS1X1QNRoAZSQkLDucnwAgY0IUAhtRInPbFtgaWnJKIj8fr/szLKzs7fdLg0ggAACCCCAgH4Ck5OTMm8IhUJGAZSUlKRfomQUVwEKobjyu6/zn3/+2SiIKisrZeeWlZXlPggyRgABBBBAAIHXBKampmSe0NPTYxRAb7zxBlIImCJAIWQKK42uJxCJRIyCqLq6WnZ2GRkZ6y3GvyOAAAIIIICAhgIzMzMyL+jq6jIKIK/Xq2GmpGQnAQohO42GC2N5+fKlURDV1NTIzu/AgQMulCBlBBBAAAEE3Cfw/fffyzVAnZ2dRgG0c+dO90GQcVwEKITiwk6nawXm5+eNgigQCMjO0OfzAYUAAggggAACGgqEw2E57geDQaMASk1N1TBTUrKzAIWQnUfHhbH9+OOPRkF07tw52Tnu37/fhRKkjAACCCCAgH4Cjx8/luP85cuXjQLorbfe0i9RMnKEAIWQI4bJfUHOzc0ZBZF6WrQqiNLT090HQcYIIIAAAghoIDA7OyvH9ZaWFqMASktL0yAzUnCyAIWQk0fPBbE/ffrUKIiizw/Yu3evCzInRQQQQAABBJwvwHHc+WOocwYUQjqPrka5PXnyRAqi1tZWvknSaFxJBQEEEEBAT4HVZ3Y0NDTIsXvfvn16JktWjhWgEHLs0LkzcHVusbq7zJUrV4yCaNeuXe7EIGsEEEAAAQRsJvDixQvjTI6zZ896mpqauNbXZmNEOP8UoBBibXCkwOq7zaidrPqmKSUlxZG5EDQCCCCAAAJOF1hYWJACSH1Zyd1fnT6a7omfQsg9Y61lpo8ePZIdL88f0HJ4SQoBBBBAwOYCPA/Q5gNEeL8pQCHECqKFwPT0tBRE3d3dPJFaixElCQQQQAABOwtEIhHjFLiqqio59mZmZto5ZGJD4DUBCiFWCq0Epqam5Gf5L774wiiIkpOTtcqRZBBAAAEEEIiXwOLiolEAVVRUyLE2KysrXuHQLwLbEqAQ2hYfC9tVYHJyUnbUoVBIdtLqOqLExES7hktcCCCAAAII2FpgeXnZuAbI7/fLsTU7O9vWMRMcAusJUAitJ8S/O1pgYmJCdtx9fX3GL0QJCQmOzongEUAAAQQQsEpgZWXF+AWovLxcjqU5OTlWdU8/CJgqQCFkKi+N20XgwYMHsiMfGBgwCiK7xEYcCCCAAAII2FFAHTfVX0lJiRw7Dx06ZMcwiQmBLQtQCG2ZjgWdKDA2NiY79eHhYdmpnz9/3olpEDMCCCCAAAKmCVy6dEmOlYWFhXKszMvLM60vGkYgngIUQvHUp++4CYyOjspOXr2rnXxjY2PcYqFjBBBAAAEE7CDQ0tIix8b8/Hw5Nqp3XgjoLEAhpPPoktu6AiMjI7LTHx8fl51+fX39usvwAQQQQAABBHQSaGtrk2Nhbm6uHAsLCgp0So9cEPhVAQohVg4EPB7P0NCQHAQePnwoB4G6ujpcEEAAAQQQ0Fqgvb1djn0HDx6UY19RUZHW+ZIcAmsFKIRYJxBYJTA4OCgHhZmZGTkonD59Gh8EEEAAAQS0Erh27Zoc6zIyMuRYV1xcrFV+JIPARgUohDYqxedcJdDf3y8HiXA4LAeJQCDgqvxJFgEEEEBAP4FgMCjHNp/PJ8e20tJS/ZIkIwQ2IUAhtAksPuo+gXv37slBY3Z2Vg4atbW17kMgYwQQQAABRwt0dHTIsSw9PV2OZWVlZY7Oh+ARiJUAhVCsJGlHa4G7d+/KQeT58+dyEKmpqdE6X5JDAAEEEHC+QGdnpxy7du/eLceuI0eOOD8pMkAghgIUQjHEpCn9Be7cuSMHlfn5eU9TU5Pn5MmT+idNhggggAACjhK4ceOGHKtSUlKkADp69Kij4idYBKwSoBCySpp+tBIIhUJykIlEInKQqa6u1io/kkEAAQQQcJ5AV1eXHJu8Xq8cm/x+v/OSIGIELBSgELIQm670E7h165YcdJaXl+Wgc+LECf2SJCMEEEAAAVsL3Lx5U45FiYmJciw6fvy4reMlOATsIkAhZJeRIA5HC/T09MhBaMeOHXIQqqiocHQ+BI8AAgggYH+B3t5eOfa8evVKTtfm2GP/MSNCewlQCNlrPIjG4QKrv5VTB6Vjx445PCPCRwABBBCwm8Dt27c9zc3NnI1gt4EhHscJUAg5bsgI2AkCnKfthFEiRgQQQMBZAlyf6qzxIlr7C1AI2X+MiNDBAtevX5fTFlJTU7lzj4PHkdARQACBeAqsvmOpOv361KlT8QyHvhHQRoBCSJuhJBE7C6hnOajTGPbs2SMFUXl5uZ3DJTYEEEAAARsI9PX1yZdpz549k2uAeIadDQaFELQSoBDSajhJxu4Cq5/urQ5qhw8ftnvIxIcAAgggYLHA/fv35cuz2dlZ+fKstrbW4gjoDgF3CFAIuWOcydJmAsFgUL7l8/l8cpArLS21WYSEgwACCCBgtUB/f78cG8LhsBwbAoGA1SHQHwKuEqAQctVwk6zdBK5evSoHvczMTDnoFRcX2y1E4kEAAQQQMFlgcHBQjgXT09NyLDhz5ozJPdI8AggoAQoh1gMEbCDQ3t4up0G89957chAsLCy0QVSEgAACCCBgpsDw8LAUQJOTk7Lvr6urM7M72kYAgTUCFEKsEgjYSKCtrU0Oirm5uXJQLCgosFF0hIIAAgggEAuBr7/+Wr78Gh8fl319fX19LJqlDQQQ2KQAhdAmwfg4AlYItLS0SEGUn58vB0n1zgsBBBBAwNkCo6Ojsm9X72rf3tjY6OyEiB4BhwtQCDl8AAlfb4GLFy/KQbOoqEgOmnl5eXonTHYIIICAhgJjY2OyLx8aGpJ9+YULFzTMkpQQcJ4AhZDzxoyIXSigDqDqT91dTh1E1alzvBBAAAEE7C2gTn1T+251Nzi171Z/vBBAwD4CFEL2GQsiQeA3BVZWVuSAqv7UA1nVATUnJwc1BBBAAAGbCXzzzTdyDZB6IGq0AEpISLBZlISDAAIUQqwDCDhMYGlpySiI/H6/HGSzs7MdlgXhIoAAAvoJqLu/qS+rQqGQUQAlJSXplygZIaCJAIWQJgNJGu4TWFxclG8c1UG3srJSDrpZWVnugyBjBBBAIM4CU1NTsi/u6emRfXFTU5MnOTk5zlHRPQIIrCdAIbSeEP+OgM0FIpGI8QtRdXW1HIQzMjJsHjXhIYAAAs4XmJmZkf1vV1eX8QuQ1+t1fmJkgIBLBCiEXDLQpKm/wMuXL42CqKamRg7KBw4c0D9xMkQAAQQsFnj06JHsbzs7O40CaOfOnRZHQXcIILBdAQqh7QqyPAI2E5ifnzcKokAgIAdpn89nsygJBwEEEHCeQDgclv1rMBg0CqDU1FTnJULECCAgAhRCrAgIaCrw4sUL4xqic+fOyUF7//79mmZLWggggIB5Ao8fP5YC6PLly3L9j9qf7tq1y7wOaRkBBCwRoBCyhJlOEIifwNzcnPELUUNDgxzE09PT4xcQPSOAAAIOEZidnZX9Z0tLi/ELUFpamkOiJ0wEEFhPgEJoPSH+HQFNBJ4+fWoURNHnWuzdu1eT7EgDAQQQiJ0A+8vYWdISAnYWoBCy8+gQGwImCDx58kQKotbWVr7hNMGXJhFAwLkCa39BV18a7du3z7kJETkCCPymAIUQKwgCLhVQ57yr5xBduXLFKIg4592lKwNpI+ByAXVNpfqCSP3V1dVxTaXL1wfSd48AhZB7xppMEfhFgbV3QVLXEKWkpKCFAAIIaC+wsLAgxY/6Uoi7bGo/3CSIwGsCFEKsFAggIAI8F4MVAQEE3CLAc9fcMtLkicBvC1AIsYYggMC/CExPT8s3pN3d3TwpnXUDAQS0EohEIsYpcFVVVbKPy8zM1CpHkkEAgY0LUAht3IpPIuAqgampKZkw9Pb2GgVRcnKyqwxIFgEE9BBYXFw0CqCKigrZp2VlZemRHFkggMCWBSiEtkzHggi4Q2ByclImEKFQSCYP6hqixMREdyRPlggg4GiB5eVl48HSfr9f9mHZ2dmOzongEUAgdgIUQrGzpCUEtBaYmJiQgqivr8/4hSghIUHrnEkOAQScKbCysmL8AlReXi77rJycHGcmQ9QIIGCaAIWQabQ0jICeAg8ePJAJxsDAgFEQ6ZkpWSGAgBMForfBLikpkX3UoUOHnJgGMSOAgAUCFEIWINMFAjoKjI2NSUE0PDwsk43z58/rmCY5IYCAQwQuXbok+6TCwkLZJ+Xl5TkkcsJEAIF4CVAIxUuefhHQRGB0dFQmH+pdTT4aGxs1yYw0EEDACQItLS2yD8rPz5d9kHrnhQACCGxEgEJoI0p8BgEE1hUYGRmRycj4+LhMRurr69ddhg8ggAACWxVoa2uTfU5ubq7scwoKCrbaFMshgIBLBSiEXDrwpI2AWQJDQ0MyOXn48KFMTurq6szqinYRQMCFAu3t7bKPOXjwoOxjioqKXKhAygggEAsBCqFYKNIGAgi8JjA4OCiTFfWAVnXL7dOnT6OEAAIIbFng2rVrcits9QBUVQAVFxdvuS0WRAABBJQAhRDrAQIImCrQ398vBVE4HJbJSyAQMLU/GkcAAb0EgsGg7EN8Pp/sQ0pLS/VKkGwQQCBuAhRCcaOnYwTcJXDv3j2ZzMzOzspkpra21l0AZIsAApsS6OjokH1Genq67DPKyso2tTwfRgABBNYToBBaT4h/RwCBmArcvXtXJjfPnz+XyU1NTU1M26cxBBBwtkBnZ6fsI3bv3i2n1aoHovJCAAEEzBCgEDJDlTYRQGBdgTt37shkZ35+XiY7J0+eXHcZPoAAAvoK3LhxQ64BSk1NlS9Jjh49qm+yZIYAArYQoBCyxTAQBALuFQiFQlIQRSIRmfxUV1e7F4PMEXChQFdXl+wDvF6v7AP8fr8LFUgZAQTiIUAhFA91+kQAgdcEbt26JZOh5eVlmQydOHECJQQQ0Fjg5s2bss0nJibKNn/8+HGNsyU1BBCwowCFkB1HhZgQcLFAb2+vnB6zY8cOmRxVVFS4WIPUEdBPQG3jqgBSL7Zx/caXjBBwkgCFkJNGi1gRcJEA3xa7aLBJ1RUCt2/fli85+NXXFcNNkgg4QoBCyBHDRJAIuFeA6wfcO/ZkrocA1wHqMY5kgYCOAhRCOo4qOSGgocD169fldBruKKXh4JKSlgKr7wypToE7deqUlnmSFAIIOFeAQsg1MGYOAAAgAElEQVS5Y0fkCLhSIPqMkbS0NLm+gGeMuHI1IGkbC/T19cmXFnNzczwrzMbjRGgIIODxUAixFiCAgCMFeOq8I4eNoDUWuH//vlwDNDs7KwVQbW2txtmSGgII6CBAIaTDKJIDAi4WCAaD8u2zz+eTyVdpaamLNUgdAesF+vv7ZRsMh8OyDQYCAeuDoEcEEEBgCwIUQltAYxEEELCfwNWrV2UylpmZKZOx4uJi+wVJRAhoJDA4OCjb3PT0tGxzZ86c0Sg7UkEAATcIUAi5YZTJEQEXCbS3t8vkLDs7WyZnhYWFLsqeVBEwX2B4eFi2scnJSdnG6urqzO+UHhBAAAETBCiETEClSQQQiL9AW1ubTNZyc3NlslZQUBD/oIgAAQcLjIyMyDY1Pj4u21R9fb2DsyF0BBBAgJslsA4ggIDmAi0tLTJ5y8/Pl8mbeueFAAIbFxgdHZVtSL2rbaixsXHjC/NJBBBAwMYC/CJk48EhNAQQiJ3AxYsXZTJXVFQkk7m8vLzYNU5LCGgoMDY2JtvM0NCQbDMXLlzQMEtSQgABNwtQCLl59MkdARcKqImd+ispKfE0NTXJqXO8EEDgnwLq1De1jai7wakCSP3xQgABBHQUoBDScVTJCQEEflNgZWVFJnrqTz2QVU30cnJyUEPA1QITExOyTagHokYLoISEBFebkDwCCOgtQCGk9/iSHQII/IbA0tKSURD5/X6Z/Km7zfFCwE0C6u5vqgAKhUJGAZSUlOQmAnJFAAGXClAIuXTgSRsBBP4psLi46GlubpbJYGVlpUwGs7KyIEJAa4GpqSlZ53t6euQ0UbXeJycna50zySGAAAKrBSiEWB8QQACB/xGIRCLGL0RVVVUyOczIyMAHAa0EZmZmZD3v6uoyfgHyer1a5UgyCCCAwEYEKIQ2osRnEEDAVQIvX740CqKamhqZLB44cMBVBiSrn8CjR49kve7s7DQKoJ07d+qXKBkhgAACGxSgENogFB9DAAH3CczPzxsFUSAQkMmjz+dzHwQZO1ogHA7LehwMBo0CKDU11dE5ETwCCCAQCwEKoVgo0gYCCGgt8OLFC+MaonPnzslkcv/+/VrnTHLOF3j8+LEUQJcvXzauAdq1a5fzEyMDBBBAIEYCFEIxgqQZBBDQX2Bubs74haihoUEml+np6fonToaOEpidnZXCvbW11fgFKC0tzVE5ECwCCCBghQCFkBXK9IEAAloJPH361CiIos9b2bt3r1Y5kozzBFgvnTdmRIwAAvEVoBCKrz+9I4CAgwWePHkiBRHfvDt4EDUIfe0vlao437dvnwaZkQICCCBgrgCFkLm+tI4AAi4QiF6L0d7ebpyKxLUYLhj4OKeorl1Thbj6q6ur49q1OI8H3SOAgPMEKIScN2ZEjAACNhVYe3cudQ1RSkqKTaMlLKcKLCwsGDfv4G6GTh1F4kYAATsIUAjZYRSIAQEEtBLgeS1aDadtkuH5VrYZCgJBAAFNBCiENBlI0kAAAfsJTE9Py2lL3d3dxilzXq/XfoESka0FIpGIcQpcVVWVrEuZmZm2jpngEEAAAScIUAg5YZSIEQEEHC0wNTUlE9menh7jeS7JycmOzongzRdYXFw0CqCKigopgLKysszvmB4QQAABlwhQCLlkoEkTAQTiLzA5OSkT21AoZPxClJSUFP/AiMBWAktLS0YB5Pf7ZV3Jzs62VYwEgwACCOggQCGkwyiSAwIIOEpgYmJCJrp9fX1GQZSQkOCoHAg29gIrKytGAVReXi7rRk5OTuw7okUEEEAAARGgEGJFQAABBOIk8ODBA5n4DgwMGAVRnEKh2zgLRG+DXVJSIqdP5ubmxjkiukcAAQT0F6AQ0n+MyRABBGwuMDY2JgXR0NCQTILPnz9v84gJL1YCly5dklthFxUVSTGcl5cXq6ZpBwEEEEBgHQEKIVYRBBBAwCYCo6OjUhCpdzUpbmxstElkhBFrgZaWFhnr/Px8GWv1zgsBBBBAwFoBCiFrvekNAQQQWFdgZGREJsnj4+MySa6vr193GT7gDIG2tjYZW3XqmxrbgoICZwROlAgggICGAhRCGg4qKSGAgB4Cw8PDctrUw4cPZdJcV1enR2IuzKK9vV0KoIMHD8rpj4WFhS5UIGUEEEDAXgIUQvYaD6JBAAEEXhMYHByUSbR6QKsqiM6cOYOSQwSuXbsmxax6AKoau+LiYodETpgIIICA/gIUQvqPMRkigIAmAv39/VIQhcNhmVQHAgFNMtMvjWAwKGPl8/lkrEpLS/VLkowQQAABhwtQCDl8AAkfAQTcJ3Dv3j2ZZM/Ozsoku7a21n0INs24o6NDxiY9PV3GpqyszKaREhYCCCCAAIUQ6wACCCDgUAH1QFZ12tXz589l0l1TU+PQTJwfdmdnpxRAaWlpMhbqgai8EEAAAQTsLUAhZO/xIToEEEBgXYE7d+7IJHx+fl4m4adOnVp3GT4QG4EbN25IMZqamir2R48ejU3DtIIAAgggYLoAhZDpxHSAAAIIWCMQCoWkIIpEIjIpr66utqZjF/bS1dUl1l6vV6z9fr8LFUgZAQQQcLYAhZCzx4/oEUAAgdcEbt26JZP05eVlmaSfOHECpRgJ3Lx5U2wTExPF9vjx4zFqmWYQQAABBKwWoBCyWpz+EEAAAYsEent7ZdKuXmrSXlFRYVHP+nWDpX5jSkYIIIAAhRDrAAIIIKC5AL9ibH2A+XVt63YsiQACCNhdgELI7iNEfAgggECMBLiuZeOQXG+1cSs+iQACCDhVgELIqSNH3AgggMAWBa5fvy6nzHGns9cBuQPfFlcqFkMAAQQcKEAh5MBBI2QEEEAgFgI8++afiuqZTKo4nJub45lMsVi5aAMBBBBwgACFkAMGiRARQAABMwU6OjqkCEhPT5cioKyszMzubNX2vXv3JPfZ2VnJvba21lbxEQwCCCCAgHkCFELm2dIyAggg4CiBYDAoRYHP55OioLS01FHxbybY/v5+yTUcDkuugUBgM4vzWQQQQAABDQQohDQYRFJAAAEEYilw9epVKRIyMzOlSCguLo5l83Fta3BwUHKbnp72NDU1eU6fPh3XeOgcAQQQQCB+AhRC8bOnZwQQQMDWAu3t7VI0HDx4UIqGwsJCW8f7W8ENDw9LLpOTk1Lc1dXVOTYXAkcAAQQQiI0AhVBsHGkFAQQQ0Fagra1Niojc3FwpIgoKChyT68jIiMQ+Pj4usdfX1zsmdgJFAAEEEDBXgELIXF9aRwABBLQRaGlpkaIiPz9figr1btfX6OioxKreVayNjY12DZW4EEAAAQTiJEAhFCd4ukUAAQScKnDx4kUpMoqKiqTIyMvLs00qY2NjEtvQ0JCcznf+/HnbxEYgCCCAAAL2EqAQstd4EA0CCCDgGAFVcKi/kpISKTrUqXPxeqlT31Qs6m5wqjhTf7wQQAABBBD4LQEKIdYPBBBAAIEtC6ysrEgBov7Ky8ulAMnJydlye5tdcGJiQvpWD0SNFkAJCQmbbYbPI4AAAgi4UIBCyIWDTsoIIIBArAWWlpaMgsjv90tRkp2dHetujPbU3d9UARQKhYwCKCkpybT+aBgBBBBAQD8BCiH9xpSMEEAAgbgJLC4uepqbm6VIqayslCIlKysrZvFMTU1J2z09PXI6nmo/OTk5Zu3TEAIIIICAewQohNwz1mSKAAIIWCYQiUSMX4iqqqqkaMnIyNhy/zMzM1JgdXd3G78Aeb3eLbfHgggggAACCFAIsQ4ggAACCJgm8PLlS6MgqqmpkSLmwIEDG+7v0aNHsnxnZ6dRAO3cuXPDy/NBBBBAAAEEfk2AQoh1AwEEEEDAdIH5+XmjIAoEAlLU+Hy+X+03HA7L54PBoFEApaammh4nHSCAAAIIuEeAQsg9Y02mCCCAQNwFXrx4IQWOOs3t3LlzUuTs37/fiOvx48fy75cvXzauAdq1a1fc4yYABBBAAAH9BCiE9BtTMkIAAQRsLzA3N2f8QtTQ0OA5deqU5/r1657W1lbjF6C0tDTb50GACCCAAALOFaAQcu7YETkCCCDgeAH1HKB/+7d/84yNjXny8vI8//mf/2npc4gcD0gCCCCAAAJbFqAQ2jIdCyKAAAIIbFWAX4S2KsdyCCCAAAKxEqAQipUk7SCAAAIIrCvANULrEvEBBBBAAAGLBCiELIKmGwQQQMDNAtw1zs2jT+4IIICAPQUohOw5LkSFAAIIaCHAc4S0GEaSQAABBLQUoBDSclhJCgEEEIivQCQSMe4KV1VVJbfCzsjI2HJQMzMzcsvt7u5u465yXq93y+2xIAIIIIAAAhRCrAMIIIAAAjETWFxcNJ4TVFlZKUVLVlZWzNqfmpqS9nt6eqRtVWAlJyfHrH0aQgABBBBwjwCFkHvGmkwRQAAB0wSWlpaMX4D8fr8UKdnZ2ab1Nzk5Kf2FQiHjF6KkpCTT+qNhBBBAAAH9BCiE9BtTMkIAAQQsE1hZWTEKoPLycilKcnJyLOtfPYdIFUR9fX1GQZSQkGBZ/3SEAAIIIOBcAQoh544dkSOAAAJxFVAFiPorLS2VIiQ3Nzdu8YyPj8s1RAMDA0ZBFLdg6BgBBBBAwBECFEKOGCaCRAABBOwjcOnSJSk6ioqKpOjIy8uzTXBjY2NSnA0NDUlsFy5csE1sBIIAAgggYC8BCiF7jQfRIIAAArYVaGlpkSIjPz9figz1btfX6OioxKreVayNjY12DZW4EEAAAQTiJEAhFCd4ukUAAQScItDW1iZFhTr1TRUVBQUFTgndMzIyIrGrU+dU7PX19Y6JnUARQAABBMwVoBAy15fWEUAAAccKtLe3SxGh7v6miojCwkLH5jI8PCyn8z18+FByqaurc2wuBI4AAgggEBsBCqHYONIKAgggoI3AtWvXpGjIzMyUoqG4uFib3AYHB6W4m56eltzOnDmjTW4kggACCCCwOQEKoc158WkEEEBAW4FgMChFgs/nkyJB3Q1O11d/f7/kGg6HJddAIKBrquSFAAIIIPArAhRCrBoIIICAywU6OjqkKEhPT5eioKyszDUi9+7dk9xnZ2cl99raWtfkTqIIIICA2wUohNy+BpA/Agi4VqCzs1OKgLS0NCkC1ANR3fpSD2RVFnNzc2JRU1PjVgryRgABBFwjQCHkmqEmUQQQQOC/Ba5fvy6T/tTUVJn0Hz16FJr/Ebhz547YzM/Pi82pU6ewQQABBBDQVIBCSNOBJS0EEEBgrUBXV5dM8r1er0zy/X4/SL8iEAqFxCoSiYhVdXU1VggggAACmglQCGk2oKSDAAIIrBW4efOmTOoTExNlUn/8+HGQNihw69YtsVteXha7EydObHBJPoYAAgggYHcBCiG7jxDxIYAAAlsU6O3tlUm8eqlJfEVFxRZbYjEsWQcQQAAB/QQohPQbUzJCAAGXC/ArhnkrAL+umWdLywgggIDVAhRCVovTHwIIIGCSANe1mAT7C81yvZV11vSEAAIImCVAIWSWLO0igAACFgmsvtNZU1OT5+TJkxb1TDfcgY91AAEEEHCuAIWQc8eOyBFAwOUCPPvGPitA9JlMu3fv9qhi1M3PZLLPqBAJAggg8NsCFEKsIQgggIDDBO7duyc3QZidnZWbINTW1josA33D7ejokLFJT0+XsSkrK9M3WTJDAAEEHC5AIeTwASR8BBBwj0B/f79MssPhsEyyA4GAe5J3WKbBYFDGyufzyViVlpY6LAPCRQABBPQXoBDSf4zJEAEEHC4wODgok+rp6Wk57er06dMOz8g94V+9elXGLjMzUwqi4uJi9yRPpggggIDNBSiEbD5AhIcAAu4VGB4e9jQ3N3sePnwok+i6ujr3Yjg88/b2dimIDh48KMVsYWGhwzMifAQQQMD5AhRCzh9DMkAAAc0ERkZGZNI8Pj4uBVB9fb1mGbo3nba2Nhnb3NxcGduCggL3YpA5AgggEGcBCqE4DwDdI4AAAlGB0dFRmSSrdzVJbmxsBEdTgZaWFhnr/Px8GWv1zgsBBBBAwFoBCiFrvekNAQQQeE1gbGxMJsVDQ0Ny2tT58+dRconApUuX5PTHoqIiKYjy8vJckjlpIoAAAvEXoBCK/xgQAQIIuFRAnfqmJsEDAwMyCVZ/vNwpoAph9VdSUiLrwaFDh9wJQdYIIICAhQIUQhZi0xUCCCCgBCYmJmTSqx6IGi2AEhISwHG5wMrKiqwX6k89kFWtGzk5OS5XIX0EEEDAPAEKIfNsaRkBBBD4F4HJyUmZ5IZCIaMASkpKQgmBfxFYWloyCiK/3y/rSnZ2NkoIIIAAAjEWoBCKMSjNIYAAAmsFpqamZGLb29trFEDJyclAIfCbAouLi7LeqNMnKysrZd3JyspCDQEEEEAgRgIUQjGCpBkEEEBgrYB6AKqayHZ3dxsFkNfrBQqBTQlEIhHjF6KqqipZl9QDWnkhgAACCGxPgEJoe34sjQACCLwm8OjRI5m4dnZ2GgXQzp07kUJgWwIvX740CqKamhpZtw4cOLCtNlkYAQQQcLMAhZCbR5/cEUAgpgLhcFgmqsFgUCap6lbYKSkpMe2DxhBYWFiQ0+XUuhYIBGRd8/l8wCCAAAIIbFKAQmiTYHwcAQQQWCvw+PFjmZS2t7cbvwDt2rULKARMFXjx4oXxC1FdXZ2se/v37ze1TxpHAAEEdBKgENJpNMkFAQQsFXjy5IlMRFtbW40CKC0tzdIY6AyBubk5oyBqaGiQdXHfvn3AIIAAAgisI0AhxCqCAAIIbFLg6dOnxsQz+hygvXv3brIVPo5AbAVYL2PrSWsIIKC/AIWQ/mNMhgggECOBtd+8q2uA0tPTY9Q6zSAQG4HZ2Vm5hohfKmPjSSsIIKCvAIWQvmNLZgggECOB6LUYanJ57tw5rsWIkSvNmCsQvXbt8uXLxs07uHbNXHNaRwABZwlQCDlrvIgWAQQsFJifnzdOgePuXBbC01VMBdbezVCdzpmamhrTPmgMAQQQcKIAhZATR42YEUDAVAGe12IqL43HSYDnW8UJnm4RQMC2AhRCth0aAkMAAasFIpGI8QtQdXW1nE6UkZFhdRj0h4CpAjMzM3INUXd3t3G3Q6/Xa2qfNI4AAgjYUYBCyI6jQkwIIGCpwOLiohRAanJYWVkpk8OsrCxLY6AzBKwWmJqakvW+p6fHuIYoOTnZ6jDoDwEEEIibAIVQ3OjpGAEE4i2wtLRk/ALk9/tlMpidnR3vsOgfAUsFJicnZTsIhULGL0RJSUmWxkBnCCCAQDwEKITioU6fCCAQV4GVlRWjACovL5fJX05OTlxjonME4i0wMTEh20VfX59RECUkJMQ7LPpHAAEETBOgEDKNloYRQMCOAmqip/5KS0tlspebm2vHMIkJgbgJjI+Py2miAwMDRkEUt2DoGAEEEDBRgELIRFyaRgAB+whcvHhRCqCioiKZ3OXl5dknOCJBwIYCY2Njss0MDQ3JNnPhwgUbRklICCCAwNYFKIS2bseSCCDgAIGWlhaZzOXn58tkTr3zQgCBjQuMjo7KNqTe1TbU2Ni48YX5JAIIIGBjAQohGw8OoSGAwNYF2traZPKmTn1Tk7eCgoKtN8aSCCDgGRkZkW1KnTqntqn6+npUEEAAAUcLUAg5evgIHgEE1gq0t7fLZE3d/U1N1goLC0FCAIEYCgwPD8s2pu42p7axurq6GLZOUwgggIB1AhRC1lnTEwIImChw9epVmZxlZmbK5Ky4uNjE3mgaAQQGBwdlm5uenpZt7syZM6AggAACjhKgEHLUcBEsAgisFQgGgzIZ8/l8MhlTd4PjhQAC1gn09/fLNhgOh2UbDAQC1nVOTwgggMA2BCiEtoHHogggED+Bjo4OmXylp6d7mpqaPIcPH45fMPSMAAKee/fuyTY5OzsrBVFtbS0qCCCAgK0FKIRsPTwEhwACawU6OztlspWWliaTLfVAVF4IIGAfAfVAVrWNPnv2TL6kqKmpsU9wRIIAAgisEqAQYnVAAAFHCFy/fl0mV6mpqVIAHT161BFxEyQCbhW4c+eObLPz8/OyzZ46dcqtFOSNAAI2FaAQsunAEBYCCPy3QFdXl0ymvF6vTKb8fj80CCDgIIFQKCTbcCQSkW24urraQdETKgII6CxAIaTz6JIbAg4WuHnzpkyeEhMT5fSaY8eOOTgbQkcAgVu3bsk2vby8LAXRiRMnQEEAAQTiKkAhFFd+OkcAgbUCvb29MllSLzVZqqioAAkBBDQSiG7jr169ki852MY1GlxSQcBhAhRCDhswwkVAVwG+LdZ1ZMkLgV8WWP2rr/rS4/jx41AhgAAClgpQCFnKTWcIILBWgOsHWCcQcLcA1wG6e/zJHoF4ClAIxVOfvhFwscDqO0qp02NOnjzpYg1SRwCBGzdueJqbm7kzJKsCAghYJkAhZBk1HSGAgBJQzxhRk53nz5/LNUA8Y4T1AgEEVgtEnxW2e/du2UccOXIEIAQQQMAUAQohU1hpFAEE1grw1HnWCQQQ2IxAR0eH3DglPT1dCqKysrLNLM5nEUAAgXUFKITWJeIDCCCwHYH+/n6ZzITDYZnMBAKB7TTHsggg4DKBYDAo+xCfzyf7kNLSUpcJkC4CCJglQCFkliztIuBygcHBQZm8TE9Pyy1yT58+7XIR0kcAge0IXLt2TU6rzczMlIKouLh4O82xLAIIIOChEGIlQACBmAoMDQ1JAfTw4UOZrNTV1cW0fRpDAAF3C7S3t8s+5uDBg7KPKSoqcjcI2SOAwJYFKIS2TMeCCCCwWmBkZEQmJ+Pj4zI5qa+vBwgBBBAwTaCtrU32Obm5ubLPKSgoMK0vGkYAAT0FKIT0HFeyQsAygdHRUZmMqHc1GWlsbLSsbzpCAAEEWlpaZB+Un58v+yD1zgsBBBDYiACF0EaU+AwCCLwmMDY2JpOP4eFhmXycP38eJQQQQCBuApcuXZJ9UmFhoeyT8vLy4hYLHSOAgDMEKIScMU5EiYBtBB48eCCTjYGBAZlsqD9eCCCAgF0E1P5J/ZWUlMj+6dChQ3YJjTgQQMBmAhRCNhsQwkHArgITExMyuVAPRI0WQAkJCXYNl7gQQMDFAisrK7K/Un/l5eWyz8rJyXGxCKkjgMAvCVAIsV4ggMBvCkxOTspkIhQKyWRC3Qo7MTERNQQQQMD2AsvLy3LLbbUP8/v9sg/Lzs62fdwEiAAC1ghQCFnjTC8IOE5gampKJg+9vb3GL0DJycmOy4OAEUAAgcXFReMXooqKCtmnZWVlAYMAAi4XoBBy+QpA+gisFVAPQFUFUHd3t1EAeb1eoBBAAAHHC0QiEaMgqqqqkn2cekArLwQQcKcAhZA7x52sEXhN4NGjRzJB6OzsNAqgnTt3IoUAAghoJ/Dy5UujIKqpqZF93oEDB7TLk4QQQOC3BSiEWEMQcLlAOByWCUEwGJTrf9SEICUlxeUqpI8AAm4QWFhYMK4hCgQCsv/z+XxuSJ0cEUDA4/FQCLEaIOBSgcePH0sB1N7ebvwCtGvXLpdqkDYCCLhZ4MWLF8YvRGfPnpUvhfbv3+9mEnJHwBUCFEKuGGaSROCfAk+ePJEDfmtrq1EApaWlQYQAAgi4XmBubs4oiBoaGmQfuW/fPte7AICArgIUQrqOLHkhsEbg6dOnxgE++hygvXv34oQAAgggwP6SdQABVwpQCLly2EnaTQKrv+FsbGyUbzjT09PdRECuCCCAwJYEZmdn5RoifkHfEh8LIWB7AQoh2w8RASKwNYHoOe/qIH7u3DkpgDjnfWuWLIUAAu4WiF5TefnyZePB0lxT6e51guz1EKAQ0mMcyQIBQ2B+ft44BY67ILFiIIAAArETWH2XzegpxqmpqbHrgJYQQMBSAQohS7npDAHzBHguhnm2tIwAAgisFuC5a6wPCOghQCGkxziShYsFVj8pvbq6Wk7byMjIcLEIqSOAAALWCMzMzMgv8F1dXcZdOL1erzWd0wsCCGxbgEJo24Q0gEB8BBYXF40HAVZWVspBOCsrKz7B0CsCCCDgYoGpqSkpiHp6eoxriJKTk10sQuoIOEOAQsgZ40SUCBgCS0tLxjVAfr9fDrrZ2dkIIYAAAgjEWWByclL2z6FQyPiFKCkpKc5R0T0CCPyaAIUQ6wYCDhFYWVkxCqDy8nJ58vn777/vkOgJEwEEEHCPwMTEhOyv+/r6jIIoISHBPQBkioBDBCiEHDJQhOluAXVAVX+lpaVyUM3NzXU3CNkjgAACDhAYHx+XfXd/f79REDkgbEJEwDUCFEKuGWoSdaLAxYsX5SBaVFQkB9G8vDwnpkHMCCCAgKsFxsbGZF8+NDQk+/ILFy642oPkEbCLAIWQXUaCOBBYJdDS0iIHzfz8fDloqndeCCCAAALOFhgdHZV9u3pX+/bGxkZnJ0T0CDhcgELI4QNI+HoJtLW1yUFSnfqmrgH64IMP9EqQbBBAAAEEPCMjI7KvV6fOqYKovr4eFQQQiIMAhVAc0OkSgbUC7e3tclBUd39TB8XCwkKQEEAAAQQ0FxgeHpZ9/7fffitfftXV1WmeMekhYC8BCiF7jQfRuEzg6tWrchDMzMyUAqi4uNhlAqSLAAIIIDA4OCjHgunpaTkWnDlzBhQEELBAgELIAmS6QGCtQDAYlIOez+eTg566GxwvBBBAAAF3C6i7y6ljQzgclmNDIBBwNwjZI2CyAIWQycA0j8BqgY6ODjnIpaeny2kQhw8fBggBBBBAAIF/Ebh//76nubnZMzs7KwVRbW0tQgggYIIAhZAJqDSJwFqBzs5OOajt2bNHDmrqgai8EEAAAQQQ+C0B9UBW9eXZs2fP5MuzmpoawBBAIIYCFEIxxKQpBNYKXL9+XQ5iqampUgAdPXoUJAQQQAABBDYlcOfOHTmWzM/Py7Hk1KlTm1qeDyOAwC8LUAixZiBggkBXV5cctLxerxy0/H6/Cb3QJAIIIICAmwRCoZAcWyKRiBxbqqur3RG8EqUAABYQSURBVJQ+uSIQcwEKoZiT0qCbBW7evCkHqcTERDmN4dixY27mIHcEEEAAARMEbt++LadbLy8vS0F04sQJE3qhSQT0F6AQ0n+MydACgd7eXjko7dixQw5KFRUVFvRKFwgggAACbhZQxx715durV6/k2FNZWelmDnJHYNMCFEKbJmMBBP4pcOvWLTkI8a0cawUCCCCAQLwEVp+NoAqi48ePxysU+kXAUQIUQo4aLoK1iwDnadtlJIgDAQQQQCAqwPWprAsIbE6AQmhzXnza5QLRO/csLCzIaQgnT550uQjpI4AAAgjYTeDGjRtyujZ3LLXbyBCP3QQohOw2IsRjS4G7d+/KKXDPnz+XAohnOdhymAgKAQQQQGCVgHqGnTp27d69W45dR44cwQcBBFYJUAixOiDwGwL37t2TgwhP92Y1QQABBBBwqkBHR4ccy9LT06UgKisrc2oqxI1ATAUohGLKSWO6CPT398tBIxwOy0EjEAjokhp5IIAAAgi4VCAYDMqxzefzybGttLTUpRKkjcB/C1AIsSYgsEpgcHBQDhIzMzNykDh9+jQ+CCCAAAIIaCVw7do1OdZlZGTIsa64uFir/EgGgY0KUAhtVIrPaS0wNDQkB4WHDx/KQaGurk7rfEkOAQQQQACB9vZ2OfYdPHhQjn1FRUWgIOAqAQohVw03ya4VGBkZkYPA+Pi4HATq6+tBQgABBBBAwFUCbW1tcizMzc2VY2FBQYGr8idZ9wpQCLl37F2d+ejoqOz01bva6Tc2Nrrag+QRQAABBBBoaWmRY2N+fr4cG9U7LwR0FqAQ0nl0ye01gbGxMdnJDw8Py07+/PnzKCGAAAIIIIDAKoFLly7JsbKwsFCOlXl5efggoKUAhZCWw0pSawUePHggO/WBgQHZqas/XggggAACCCDw6wLquKn+SkpK5Lh56NAhuBDQSoBCSKvhJJm1AhMTE7IT7+vrMwqghIQEoBBAAAEEEEBgAwIrKytyHFV/5eXlcizNycnZwJJ8BAH7C1AI2X+MiHALApOTk7LTDoVCnqamJtlxJyYmbqElFkEAAQQQQACB5eVlT3Nzsxxb/X6/HFezs7OBQcDRAhRCjh4+gl8rMDU1JTvp3t5e4xeg5ORkoBBAAAEEEEAgBgKLi4vGL0Qff/yxfNmYlZUVg5ZpAgHrBSiErDenRxMEpqenZcfc3d1tFEBer9eEnmgSAQQQQAABBCKRiFEQVVVVybE3MzMTGAQcJUAh5KjhIti1Ao8ePZIdcWdnp1EA7dy5EygEEEAAAQQQsEDg5cuXRkFUU1Mjx+IDBw5Y0DNdILB9AQqh7RvSQhwEwuGw7HiDwaBxDVBKSkocIqFLBBBAAAEEEFhYWJDjsrqOKBAISEHk8/mAQcDWAhRCth4eglsr8PjxY9nJXrlyxfgFaNeuXUAhgAACCCCAgA0EXrx4YfxCdPbsWfmycv/+/TaIjBAQeF2AQoi1whECT548kR1ra2urUQClpaU5InaCRAABBBBAwG0Cc3NzRkHU0NAgx+59+/a5jYF8bS5AIWTzAXJ7eE+fPjV2pNEHoe7du9ftLOSPAAIIIICAIwQ4jjtimFwbJIWQa4fe3omv/iapsbFRvklKT0+3d9BEhwACCCCAAAK/KDA7OytfbLa0tHBmB+uIbQQohGwzFASiBH788UfjF6Bz587JzpJzi1k3EEAAAQQQ0ENAXeurCqLLly8bBdFbb72lR3Jk4TgBCiHHDZmeAc/PzxsFEHeb0XOMyQoBBBBAAIGowOq7v0ZPfU9NTQUIAUsFKIQs5aaztQJrnz+g7i7zzjvvAIUAAggggAACLhDgeYAuGGQbp0ghZOPB0Tm01U+krq6ulp/HMzIydE6Z3BBAAAEEEEDgVwRmZmbkzJCuri7jlDmv14sXAqYKUAiZykvjawV+/vln4xS4yspK2dllZWUBhQACCCCAAAIIeKampmSe0NPTYxREb7zxBjIImCJAIWQKK42uFVhaWjIKIL/fLzu37OxsoBBAAAEEEEAAgdcEJicnZd4QCoWMgigpKQkpBGIqQCEUU04aWyuwsrJiFEDl5eXyhOn3338fKAQQQAABBBBAYF2Bb775xtPc3Ozp6+szCqKEhIR1l+MDCGxEgEJoI0p8ZksC6psc9VdaWio7r9zc3C21w0IIIIAAAggg4G6B8fFxmVN8+eWX8qWqmlfwQmC7AhRC2xVk+dcELl68KDuroqIi2VHl5eWhhAACCCCAAAIIbFtgbGxM5hhDQ0Myx7hw4cK226QB9wpQCLl37GOeuXpatNo55efny85JvfNCAAEEEEAAAQRiLTA6OipzDvWu5hyNjY2x7oL2XCBAIeSCQTY7xba2NtkZqVPf1M/VH3zwgdld0j4CCCCAAAIIIOD5+uuv5RoideqcKojq6+tRQWDDAhRCG6big2sF2tvbZefz3nvvyc6nsLAQJAQQQAABBBBAwHKB4eFh+VL222+/lS9l6+rqLI+BDp0nQCHkvDGLe8RXr16VnU1mZqYUQMXFxXGPiQAQQAABBBBAAIHBwUGZo0xPT8sc5cyZM6Ag8KsCFEKsHBsWCAaDsnPx+Xyyc1F3g+OFAAIIIIAAAgjYTaC/v1/mLOFwWOYsgUDAbiESjw0EKIRsMAh2D6Gjo0N2Junp6fJz8+HDh+0eMvEhgAACCCCAAAKe+/fvy2n8s7OzUhDV1taigoAhQCHEyvCrAp9//rkUQHv27JGdh3ogKi8EEEAAAQQQQMBpAuqBrGpO8+zZM5nTfPLJJ05LgXhNEKAQMgHV6U1ev35ddhapqamyszh69KjTUyJ+BBBAAAEEEEDAc+fOHZnjzM/Pyxzn1KlTqLhYgELIxYO/NvWuri7ZOXi9Xtk5+P1+dBBAAAEEEEAAAe0EQqGQzHkikYjMeaqrq7XLkYTWF6AQWt9I+0/cvHlTdgZJSUmyMzh27Jj2OZMgAggggAACCCBw+/ZtuYZoeXlZ5kAnTpwAxUUCFEIuGuy1qfb09EgBtGPHDtn4KyoqXKxB6ggggAACCCDgVoHe3l6ZE7169UrmRJWVlW6lcFXeFEKuGu7/TvbWrVuysfPthwsHn5QRQAABBBBA4FcFomfJJCYmSkF0/PhxtDQWoBDSeHDXpsb5sC4abFJFAAEEEEAAgS0LcN30lukctSCFkKOGa2vBRu+QsrCwIN9unDx5cmsNsRQCCCCAAAIIIOAigRs3bshZNCkpKdxJV8NxpxDScFCjKd29e1c23ufPn8vGW1NTo3G2pIYAAggggAACCJgj0NnZKXOq3bt3y5zqyJEj5nREq5YKUAhZym1NZ/fu3ZONlacoW+NNLwgggAACCCDgDoGOjg6ZY6Wnp0tBVFZW5o7ENc2SQkijge3v75eNMxwOe5qamjyffvqpRtmRCgIIIIAAAgggYA+BYDAocy6fzycFUWlpqT0CI4pNCVAIbYrLnh8eHByUjXFmZkY2xtOnT9szUKJCAAEEEEAAAQQ0Erh27ZrMwTIyMmQOVlxcrFF2+qdCIeTgMR4aGpKN7+HDh7Lx1dXVOTgbQkcAAQQQQAABBJwp0N7eLnOygwcPypysqKjImYm4LGoKIQcO+MjIiGxs4+PjsrHV19c7MAtCRgABBBBAAAEE9BJoa2uTOVpubq7M0QoKCvRKULNsKIQcNKCjo6Oycal3dQ1QQ0ODg6InVAQQQAABBBBAwB0Cra2tnubmZk9+fr4UROqdl/0EKITsNyavRTQ2NiYb01dffSUb0/nz5x0QNSEigAACCCCAAALuFrh06ZJ8if3hhx/Kl9h5eXnuBrFZ9hRCNhuQ1eE8ePBANp6BgQEpgNQfLwQQQAABBBBAAAFnCaj5nPorKSmR+dyhQ4eclYCm0VII2XBgJyYmZGPp6+szCqCEhAQbRkpICCCAAAIIIIAAAhsRWFlZkfmd+isvL5c5Xk5OzkYW5TMmCVAImQS7lWYnJydl4wiFQvLzqdpAEhMTt9IUyyCAAAIIIIAAAgjYUGB5eVnme+qyB7/fL/O97OxsG0aqf0gUQjYY46mpKdkYvvjiC+MXoOTkZBtERggIIIAAAggggAACZggsLi4avxB9/PHHMgd89913zeiKNn9FgEIojqvG9PS0bADd3d1GAeT1euMYEV0jgAACCCCAAAIIWCkQiUSMgqiqqkrmhJmZmVaG4Nq+KITiMPSPHj2SFb6zs1NWdnUa3JtvvhmHSOgSAQQQQAABBBBAwA4CL1++NAqimpoamSMeOHDADqFpGwOFkIVDGw6HZQUPBoPGNUApKSkWRkBXCCCAAAIIIIAAAnYWWFhYMK4hCgQCUhD5fD47h+zY2CiELBi6H374QVboK1euGKfA7dq1y4Ke6QIBBBBAAAEEEEDAiQIvXrwwfiE6e/aszCHffvttJ6Zi25gphEwcmidPnsgKrJ4uHH0OUFpamok90jQCCCCAAAIIIICATgJzc3NGQdTQ0CBzyn379umUYtxyoRAygf7p06fGChu9Buj3v/+9CT3RJAIIIIAAAggggIAbBP7+97/LXYbVl+zRL9j37t3rhtRNy5FCKIa0qyv2xsZGWUnT09Nj2ANNIYAAAggggAACCLhZYHZ2VoqhlpYWzjja5opAIbRNQLX4jz/+aPwCdO7cOVkp9+/fH4OWaQIBBBBAAAEEEEAAgdcFHj9+LPPPy5cvGwXRW2+9BdUmBCiENoG19qPz8/NGAcRdPbYByaIIIIAAAggggAACWxJYfVfi6ClzqampW2rLbQtRCG1hxNfe5109B+idd97ZQkssggACCCCAAAIIIIDA9gW+//57uYYo+pxKVRTt3Llz+w1r3AKF0CYGN/rkX7WS/elPf5KfITMyMjbRAh9FAAEEEEAAAQQQQMA8gZmZGTlj6S9/+Yvx3Eqv12tehw5umUJoA4P3888/G6fAVVZWSgGUlZW1gSX5CAIIIIAAAggggAAC1gtMTU3J/LWnp8e4huiNN96wPhAb90gh9BuDs7S0ZBRAfr9fVqLs7GwbDyehIYAAAggggAACCCDwT4HJyUmZz4ZCIaMgSkpKgsjj8VAI/cJqsLKyYhRA5eXl8rPi+++/zwqDAAIIIIAAAggggIAjBb755hu5hqivr88oiBISEhyZS6yCphBaI6kqZrWSfPTRR7KS5ObmxsqadhBAAAEEEEAAAQQQiKvA+Pi4fOH/5ZdfylxXfeHv1heF0P+M/MWLF2WlKCoqkpUiLy/PresEeSOAAAIIIIAAAghoLjA2NiZz36GhIZn7XrhwQfOMX0/P9YWQeiqvWgny8/NlJVDvvBBAAAEEEEAAAQQQcIPA6OiozIXVu5oLNzY2uiFtydG1hVBbW5sM+qFDh2TQP/jgA9cMOokigAACCCCAAAIIILBa4Ouvv5bLQ9Spc2puXF9frz2Q6wqhy5cvSwH03nvvySAXFhZqP8gkiAACCCCAAAIIIIDARgSGh4dlrvztt9/KXPncuXMbWcyRn3FNIXT16lUZ1MzMTBnU4uJiRw4YQSOAAAIIIIAAAgggYLbA4OCgzJ2np6dl7nzmzBmzu7S8fe0LoWAwKIPo8/lkEEtLSy1HpkMEEEAAAQQQQAABBJwo0N/fL3PpcDgsc+lAIODENH4xZm0LoY6ODhm0ffv2yaAdPnxYm0EjEQQQQAABBBBAAAEErBS4f/++zK2fPHkic+va2loruzelL+0Koc8//1wGac+ePTJI6oGovBBAAAEEEEAAAQQQQGD7AuqBrGqu/ezZM5lrf/LJJ9tvNE4taFMIXb9+XQYlNTVVBuXo0aNxIqVbBBBAAAEEEEAAAQT0Frhz547Mvefn52XuferUKccl7PhCqKurSwbB6/XKIPj9fscNAgEjgAACCCCAAAIIIOBEgVAoJHPxSCQic/Hq6mrHpOHYQujmzZuCnpSUJOjHjh1zDDqBIoAAAggggAACCCCgk8Dt27dlbr60tCRz8xMnTtg+PccVQj09PYK8Y8cOQa6oqLA9MgEigAACCCCAAAIIIOAGgd7eXpmrv3r1SubqlZWVtk3bMYXQrVu3BHV5edkxVaZtR53AEEAAAQQQQAABBBAwUSB69lZiYqLM3Y8fP25ib1tr2vaF0OrzDpuamjxVVVVby5SlEEAAAQQQQAABBBBAwFKB7u5uT3Nzsy2v57dtIRS9E8XCwoJUkSdPnrR00OgMAQQQQAABBBBAAAEEYiNw48YNObsrJSXFNnd4tl0hdPfuXUF6/vy5INXU1MRGn1YQQAABBBBAAAEEEEAgrgKdnZ0y19+9e7fM9Y8cORK3eGxTCN27d09QZmdntXlabdxGlY4RQAABBBBAAAEEELCxQEdHh8z909PTZe5fVlZmebRxL4T6+/sFIRwOe9Q1QJ9++qnlCHSIAAIIIIAAAggggAAC1gt89tlncg2Rz+eTgqi0tNSyIOJWCA0ODkrSf/vb3yTp06dPW5Y0HSGAAAIIIIAAAggggIB9BK5duyY/jvzhD3+QH0eKi4tND87yQmhoaEiSfPjwoRRAdXV1pidJBwgggAACCCCAAAIIIGB/gfb2dqkVDh48KLVCUVGRaUFbVgiNjIxIUuPj45JUfX29aUnRMAIIIIAAAggggAACCDhXoK2tTWqH3NxcqR0KCgpinozphdDo6Kgkod7Vz1wNDQ0xT4IGEUAAAQQQQAABBBBAQD+B1tZWuZwmPz9fCiL1HquXaYXQX//6VymAvvrqKwn6/PnzsYqZdhBAAAEEEEAAAQQQQMBFApcuXZLa4sMPP5Ta4o9//OO2s495IfTgwQMJcmBgQIJUf7wQQAABBBBAAAEEEEAAge0KqDpD/ZWUlEidcejQoS03GbNCaGJiQoLq6+uToNRpcL/73e+2HBgLIoAAAggggAACCCCAAAJrBf7xj3/I6XKq9igvL5faIycnZ9NQ2y6EJicnJYhQKCTFjwokMTFx04GwAAIIIIAAAggggAACCCCwUYHl5WWpQ1RR5Pf7pQ7Jzs7e6OKeLRdC3333nXT8xRdfGKfAJScnb7hjPogAAggggAACCCCAAAIIbFdgcXFR6hL19/HHH0tt8u67767b7KYLoenpaemku7vbKIC8Xu+6HfEBBBBAAAEEEEAAAQQQQMAsgUgkYhREVVVVUqtkZmb+ancbLoQePXokDXd2dhrXAL355ptm5UG7CCCAAAIIIIAAAggggMCmBX766SfjGqKamhqpXQ4cOPBaO+sWQuFwWAqgzz77zPgFKCUlZdMBsQACCCCAAAIIIIAAAgggYJXAwsKC8QvRp59+KrWMz+czuv/VQuiHH36QBa9cuWIUQLt27bIqbvpBAAEEEEAAAQQQQAABBLYt8OLFC6MgOnv2rNQ2b7/99i/fLKEg/3971FNco88BSktL23YANIAAAggggAACCCCAAAIIxEtgbm7OKIgaGho8I6P/zzM68l+eHX/+859f/fnPf45XXPSLAAIIIIAAAggggAACCJguoB758+rVK8/TZ8891zv/r2fHK/W/PB6PuriImyCY7k8HCCCAAAIIIIAAAgggEEeBaN3z/wFbg+CF7gcARQAAAABJRU5ErkJggg==");
		return imgdataDto;
	}


	@Override
	public List<Integer> findBigImageForEatery(int eateryId) {
		List<Integer> imagesDataId = imageDataDAO.findBigByEateryId(eateryId);
		return imagesDataId;
	}

	@Override
	public List<Integer> findSmallImageForEatery(int eateryId) {
		List<Integer> imagesDataId = imageDataDAO.findSmallByEateryId(eateryId);
		return imagesDataId;
	}

	@Override
	public void review(ReviewDTO rdto) throws GGourmandException {
		Review review = new Review();
		review.setComment(rdto.getComment());
		review.setRating(rdto.getRating());
		Booking booking = bookingDAO.read(rdto.getBookingID());
		review.setBooking(booking);
		
		reviewDAO.create(review);
		
	}
	
	private ReviewDTO transform(Review r) {
		ReviewDTO rev = new ReviewDTO();
		rev.setComment(r.getComment());
		rev.setDateTime(r.getBooking().getDateTime());
		rev.setFirstName(r.getBooking().getCustomer().getFirstName());
		rev.setLastName(r.getBooking().getCustomer().getLastName());
		rev.setNumberOfPeople(r.getBooking().getNbOfCustomer());
		rev.setRating(r.getRating());
		rev.setUserName(r.getBooking().getCustomer().getUsername());
		return rev;
	}
	
	
	
/////////////////////////////////////////////////////////////////////////////////////////////////////	
	@Override
	public List<CityDTO> getAllCities() {
		List<CityDTO> result = new ArrayList<CityDTO>();
		List<City> cities = cityDAO.listAll();
		cities.stream().forEach(c -> result.add(transform(c)));
		return result;
	}

	@Override
	public List<CityDTO> getAllCitiesLike(String beginNameCity) {
		List<CityDTO> result = new ArrayList<CityDTO>();
		List<City> cities = cityDAO.listAll(beginNameCity);
		cities.stream().forEach(c -> result.add(transform(c)));
		return result;
	}
	@Override
	public List<CityDTO> getAllCitiesForemost() {
		List<CityDTO> result = new ArrayList<CityDTO>();
		List<City> cities = cityDAO.listAllforemost();
		cities.stream().forEach(c -> result.add(transform(c)));
		return result;
	}
	
	
	private CityDTO transform(City c) {
		CityDTO cityDto = new CityDTO();
		cityDto.setId(Integer.toString(c.getId()));
		cityDto.setName(c.getName());
		cityDto.setForemost(String.valueOf(c.isForeMost()));
		cityDto.setRegion_name(c.getRegion().getName());
		cityDto.setCountry_name(c.getCountry().getName());
//		if (c.isForemost()) {
//			cityDto.setImageId(imageDataDAO.findImageDataCityIdByTargetId(c.getId()));
//		} else {
//			cityDto.setImageId(null);
//		}

		return cityDto;
	}
	

	@SuppressWarnings("unused")
	private ImageDataDTO transform(ImageData imgdata){
		ImageDataDTO imgdataDto = new ImageDataDTO();
		imgdataDto.setSize(imgdata.getSize());
		imgdataDto.setContent(imgdata.getBase64URL());
		return imgdataDto;
	}
	


	@Override
	public List<EateryDTO> findEateryByCriteria(SearchCriteriaDTO criteria) {
		SearchCriteria criter = new SearchCriteria();
		criter = parseCrit(criteria);
		EateryResult daoresult = eateryDAO.findByCriteria(criter);
		List<EateryDTO> result = daoresult.getEateries().stream().map(e -> transform(e, false))
				.collect(Collectors.toList());
		return sortByCriteria(result, criteria.getOrderBy());
	}
	
	private SearchCriteria parseCrit(SearchCriteriaDTO criteria) {
		SearchCriteria criter = new SearchCriteria();
		criter.setName(criteria.getName());
		criter.setCityId(criteria.getCityId());
		criter.setCookingStyleId(criteria.getCookingStyleId());
		return criter;
	}

	private List<EateryDTO> sortByCriteria(List<EateryDTO> res, OrderDTO orderBy) {
		switch (orderBy) {
		case CITY:
			Comparator<EateryDTO> byCity = (EateryDTO o1, EateryDTO o2) -> o1.getCity().compareTo(o2.getCity());
			res.sort(byCity);
			break;
		case REGION:
			Comparator<EateryDTO> byRegion = (EateryDTO o1, EateryDTO o2) -> o1.getRegion().compareTo(o2.getRegion());
			res.sort(byRegion);
			break;
		case COOKINGSTYLE:
			Comparator<EateryDTO> byCookingStyle = (EateryDTO o1, EateryDTO o2) -> o1.getCookingStyle()
					.compareTo(o2.getCookingStyle());
			res.sort(byCookingStyle);
			break;
		case PRICE:
			Comparator<EateryDTO> byPrice = (EateryDTO o1, EateryDTO o2) -> o1.getPrice().compareTo(o2.getPrice());
			res.sort(byPrice);
			break;
		default:
			Comparator<EateryDTO> byName = (EateryDTO o1, EateryDTO o2) -> o1.getName().compareTo(o2.getName());
			res.sort(byName);
			break;
		}
		return res;
	}

}




